import pandas as pd
from datetime import datetime, timedelta


def ingest_data():
    """
    Load the air pollution measurement data from the URL specified and filter
    the DataFrame to include only the data from yesterday. The data is loaded
    into a DataFrame, and then the date of yesterday is calculated. Subsequently,
    the rows where the 'Datum' column equals yesterday's date are filtered. Finally,
    yesterday's data is saved to a CSV file named 'zrh-YYYY-MM-DD.csv', where
    'YYYY-MM-DD' represents yesterday's date.

    Returns:
    None

    (docstring generated by ChatGPT 3.5)
    """

    # load the growing file
    df = pd.read_csv(
        'https://data.stadt-zuerich.ch/dataset/sid_dav_verkehrszaehlung_miv_od2031/download/sid_dav_verkehrszaehlung_miv_OD2031_2024.csv',
        usecols=['MSID', 'MessungDatZeit', 'LieferDat', 'AnzFahrzeuge',
                 'AnzFahrzeugeStatus'],
        parse_dates=['MessungDatZeit', 'LieferDat']
    )

    # Calculate the date of yesterday
    two_days_before_today = datetime.now().date() - timedelta(days=2)

    # Filter rows where 'Datum' equals to yesterday
    filtered_df = df[df['MessungDatZeit'].dt.date == two_days_before_today]

    print(filtered_df.head(20))


if __name__ == "__main__":
    ingest_data()
